### **Import**

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.3.3


### **Creating Arrays**

In [2]:
# 1D Array
a = np.array([1, 2, 3, 4, 5])
print("1D Array:", a)

# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# 3D Array
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("3D Array:\n", c)

print("Shape of 2D:", b.shape)
print("Dtype:", a.dtype)
print("Dimensions:", c.ndim)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of 2D: (2, 3)
Dtype: int64
Dimensions: 3


### **Built-in Functions**

In [3]:
print("Zeros:\n",       np.zeros((3,3)))
print("Ones:\n",        np.ones((2,4)))
print("Arange:",        np.arange(0, 20, 2))
print("Linspace:",      np.linspace(0, 1, 6))
print("Identity:\n",    np.eye(3))
print("Random Int:\n",  np.random.randint(1, 100, (3,3)))
print("Random Float:\n",np.random.rand(3,3).round(2))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange: [ 0  2  4  6  8 10 12 14 16 18]
Linspace: [0.  0.2 0.4 0.6 0.8 1. ]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Int:
 [[27 58 81]
 [64 11 37]
 [76 35 82]]
Random Float:
 [[0.01 0.79 0.12]
 [0.34 0.97 0.11]
 [0.95 0.84 0.29]]


### **Array Operations**

In [4]:
x = np.array([10, 20, 30, 40, 50])

print("Sum:",         np.sum(x))
print("Mean:",        np.mean(x))
print("Median:",      np.median(x))
print("Std Dev:",     np.std(x))
print("Variance:",    np.var(x))
print("Min:",         np.min(x), " Max:", np.max(x))
print("Cumsum:",      np.cumsum(x))
print("Squared:",     x ** 2)
print("Square Root:", np.sqrt(x))
print("Log:",         np.log(x).round(2))

Sum: 150
Mean: 30.0
Median: 30.0
Std Dev: 14.142135623730951
Variance: 200.0
Min: 10  Max: 50
Cumsum: [ 10  30  60 100 150]
Squared: [ 100  400  900 1600 2500]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Log: [2.3  3.   3.4  3.69 3.91]


### **Indexing, Slicing, Reshaping**

In [5]:
arr = np.arange(1, 13).reshape(3, 4)
print("Matrix:\n", arr)
print("Row 0:", arr[0])
print("Col 2:", arr[:, 2])
print("Element [1][2]:", arr[1][2])
print("Slice [0:2, 1:3]:\n", arr[0:2, 1:3])
print("Flattened:", arr.flatten())

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row 0: [1 2 3 4]
Col 2: [ 3  7 11]
Element [1][2]: 7
Slice [0:2, 1:3]:
 [[2 3]
 [6 7]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


### **Boolean Masking**

In [6]:
data = np.array([5, 15, 25, 35, 45, 55])
print("Values > 20:",    data[data > 20])
print("Even numbers:",   data[data % 10 == 5])
print("Between 15-45:",  data[(data >= 15) & (data <= 45)])

Values > 20: [25 35 45 55]
Even numbers: [ 5 15 25 35 45 55]
Between 15-45: [15 25 35 45]


### **Matrix Operations**

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n",       A + B)
print("Multiplication:\n", A * B)
print("Dot Product:\n",    np.dot(A, B))
print("Transpose:\n",      A.T)
print("Determinant:",      round(np.linalg.det(A), 2))
print("Inverse:\n",        np.linalg.inv(A).round(2))

Addition:
 [[ 6  8]
 [10 12]]
Multiplication:
 [[ 5 12]
 [21 32]]
Dot Product:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
